# Generated by Django 3.2.21 on 2023-10-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('В ожидании', 'В ожидании'), ('В работе', 'В работе'), ('Готово', 'Готово')], default='В ожидании', max_length=20)),
                ('descrption', models.CharField(max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FileImageForOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_file', models.FileField(upload_to='file/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='order.order')),
            ],
        ),
    ]
